### ISSUE TITLE
Optimized class loader always false

### ISSUE THREAD

**Issue by marktopper** [arrilot/laravel-systemcheck#3]
```
Laravel Framework version 5.2.39
PHP 7.0.7 (cli) (built: May 27 2016 11:13:44) ( NTS )
arrilot/laravel-systemcheck 1.0.0
```

<img width="652" alt="skaermbillede 2016-06-22 19 20 34" src="https://cloud.githubusercontent.com/assets/2232539/16276643/938f0fc6-38af-11e6-8a48-36534dae0aca.png">

**Comment by arrilot** [comment]
Sorry for the late answer.

This happens because `php artisan optimize` does not create optimized class loader if `app.debug` is set to true.
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Console/OptimizeCommand.php#L62
Set `app.debug` to false or use `php artisan optimize --forse`
